import type { NativeStackNavigationProp } from '@react-navigation/native-stack';

type RootStackParamList = {
  Home: undefined;
  Button: undefined;
  Typography: undefined;
  Input: undefined;
  Card: undefined;
  Chip: undefined;
  Modal: undefined;
  BottomSheet: undefined;
  Checkbox: undefined;
  Radio: undefined;
  Switch: undefined;
  List: undefined;
  Select: undefined;
  Toast: undefined;
  InputPassword: undefined;
  CheckBox: undefined;
  RadioButton: undefined;
  Drawing: undefined;
  DatePicker: undefined;
  Calendar: undefined;
  Example: undefined;
  AvatarGroup: undefined;
  Avatar: undefined;
  Footer: undefined;
  Container: undefined;
  Leave: undefined;
  LeaveDetail: undefined;
  LeaveForm: undefined;
  SpSignature: undefined;
  SpDetail: undefined;
  Badge: undefined;
  Alert: undefined;
  TextArea: undefined;
  Accordion: undefined;
  DropDown: undefined;
  Login: undefined;
  ForgotPassword: undefined;
};

export type NavigationProps = NativeStackNavigationProp<RootStackParamList>;
