import type { NativeStackNavigationProp } from '@react-navigation/native-stack';

type RootStackParamList = {
  Home: undefined;
  Button: undefined;
  Typography: undefined;
  Input: undefined;
  InputOtp: undefined;
  Card: undefined;
  Chip: undefined;
  CounterButton: undefined;
  Modal: undefined;
  BottomSheet: undefined;
  Checkbox: undefined;
  Radio: undefined;
  Switch: undefined;
  List: undefined;
  Label: undefined;
  Select: undefined;
  Toast: undefined;
  InputPassword: undefined;
  CheckBox: undefined;
  RadioButton: undefined;
  Drawing: undefined;
  DatePicker: undefined;
  YearPicker: undefined;
  MonthPicker: undefined;
  TimePicker: undefined;
  Calendar: undefined;
  Example: undefined;
  AvatarGroup: undefined;
  Avatar: undefined;
  Footer: undefined;
  Container: undefined;
  Leave: undefined;
  LeaveDetail: undefined;
  LeaveForm: undefined;
  SpSignature: undefined;
  SpDetail: undefined;
  Badge: undefined;
  Alert: undefined;
  TextArea: undefined;
  Accordion: undefined;
  DropDown: undefined;
  Login: undefined;
  ForgotPassword: undefined;
  LeaveApprove: undefined;
  TimeLine: undefined;
  Tab: undefined;
  TabDefault: undefined;
  TabSticky: undefined;
  TextEditor: undefined;
  Step: undefined;
  Icons: undefined;
  Skeleton: undefined;
  BadgeIcon: undefined;
  InputFile: undefined;
  PdfView: undefined;
  InputSelect: undefined;
};

export type NavigationProps = NativeStackNavigationProp<RootStackParamList>;
